--ozone-platform-hint=wayland
#--gtk-version=4
--password-store=kwallet6
#--use-gl=angle
#--use-angle=vulkan
#--enable-accelerated-video-decode
# --disable-sync-preferences
--enable-features=VaapiVideoDecoder,UseMultiPlaneFormatForHardwareVideo,WebRTCPipeWireCapturer,WaylandWindowDecorations,WaylandPerSurfaceScale,WaylandUiScale
