# Copy the mtime
--mtime

# Save all videos under YouTube directory in your home directory
-o ~/YouTube/%(title)s.%(ext)s

# Allow js execution
--remote-components="ejs:github"
# Enable Proof Of 
--extractor-args="youtubepot-bgutilhttp:base_url=http://127.0.0.1:4416" --cookies-from-browser=chromium+kwallet6
