#################
### AUTOSTART ###
#################
## Hyprland Plugins
exec-once = hyprpm reload -n

## Daemons
# Kwallet for secrets
exec-once = uwsm app -t service -s background-graphical.slice /usr/lib/pam_kwallet_init
# pypr is a utility helper for hyprland
exec-once = uwsm app -t service -s background-graphical.slice -u pypr.service pypr
# Notification Daemon
exec-once = systemctl --user start mako.service
# Idle service
exec-once = systemctl --user start hypridle.service
# Polkit Service
exec-once = systemctl --user start hyprpolkitagent.service
# HyprSunset changes color temp based on time of day
exec-once = systemctl --user start hyprsunset.service
# General panel/bar for wayland
exec-once = systemctl --user start waybar.service

## Wallpaper one of the following 3
# exec-once = systemctl --user start hyprpaper.service 
exec-once = uwsm app -t service -s b -u awww.service awww-daemon
# exec-once = uwsm app waypaper --restore

# Clipboard
exec-once = uwsm app -t service -s b -u clipvault.service -- wl-paste --watch clipvault store --min-entry-length 2 --max-entries 200 --max-entry-age 2d

# Applications
exec-once = uwsm app -- openrgb --startminimized

