monitorv2 {
    output=desc:$mon_dell_2
    mode=$dell_mode
    position=0x250
    scale=1
}

monitorv2 {
  output = desc:$mon_dell_1
  mode = $dell_mode
  position = 1920x0
  scale = 1
  transform = 1
}

monitorv2 {
  output=desc:$mon_gigabyte
  mode=3840x2160@100.00
  position=3000x0
  scale=1.33
  bitdepth=8
  cm=auto
  vrr= 3
}
