# https://github.com/Duckonaut/split-monitor-workspaces
##! Workspace navigation
# Switching
#/# bind = $mod, Hash,, # Focus workspace # (1, 2, 3, 4, ...)
bind = $mod, 1, split-workspace, 1 # [hidden]
bind = $mod, 2, split-workspace, 2 # [hidden]
bind = $mod, 3, split-workspace, 3 # [hidden]
bind = $mod, 4, split-workspace, 4 # [hidden]
bind = $mod, 5, split-workspace, 5 # [hidden]
bind = $mod, 6, split-workspace, 6 # [hidden]
bind = $mod, 7, split-workspace, 7 # [hidden]
bind = $mod, 8, split-workspace, 8 # [hidden]
bind = $mod, 9, split-workspace, 9 # [hidden]
bind = $mod, 0, split-workspace, 10 # [hidden]

#/# bind = Ctrl+$mod, ←/→,, # Workspace: focus left/right
bind = Ctrl+$mod, Right, split-workspace, e+1 # [hidden]
bind = Ctrl+$mod, Left, split-workspace, e-1 # [hidden]
#/# bind = $mod, Scroll ↑/↓,, # Workspace: focus left/right
# Scroll through existing workspaces with mod + scroll
bind = $mod, mouse_down, split-workspace, e+1
bind = $mod, mouse_up, split-workspace, e-1
bind = Ctrl+$mod, mouse_up, split-workspace, e+1 # [hidden]
bind = Ctrl+$mod, mouse_down, split-workspace, e-1 # [hidden]
#/# bind = $mod, Page_↑/↓,, # Workspace: focus left/right
bind = $mod, Page_Down, split-workspace, e+1 # [hidden]
bind = $mod, Page_Up, split-workspace, e-1 # [hidden]
bind = Ctrl+$mod, Page_Down, split-workspace, e+1 # [hidden]
bind = Ctrl+$mod, Page_Up, split-workspace, e-1 # [hidden]

##! Workspace management
# Move window to workspace $mod + Alt + [0-9]
#/# bind = $mod+Alt, Hash,, # Window: move to workspace # (1, 2, 3, 4, ...)
bind = $mod SHIFT, 1, split-movetoworkspace, 1 # [hidden]
bind = $mod SHIFT, 2, split-movetoworkspace, 2 # [hidden]
bind = $mod SHIFT, 3, split-movetoworkspace, 3 # [hidden]
bind = $mod SHIFT, 4, split-movetoworkspace, 4 # [hidden]
bind = $mod SHIFT, 5, split-movetoworkspace, 5 # [hidden]
bind = $mod SHIFT, 6, split-movetoworkspace, 6 # [hidden]
bind = $mod SHIFT, 7, split-movetoworkspace, 7 # [hidden]
bind = $mod SHIFT, 8, split-movetoworkspace, 8 # [hidden]
bind = $mod SHIFT, 9, split-movetoworkspace, 9 # [hidden]
bind = $mod SHIFT, 0, split-movetoworkspace, 10 # [hidden]

bind = Ctrl+$mod+Shift, Right, split-movetoworkspace, e+1 # [hidden]
bind = Ctrl+$mod+Shift, Left, split-movetoworkspace, e-1 # [hidden]
#/# bind = $mod+Shift, Scroll ↑/↓,, # Window: move to workspace left/right
bind = $mod+Shift, mouse_down, split-movetoworkspace, e-1 # [hidden]
bind = $mod+Shift, mouse_up, split-movetoworkspace, e+1 # [hidden]
bind = $mod+Alt, mouse_down, split-movetoworkspace, e-1 # [hidden]
bind = $mod+Alt, mouse_up, split-movetoworkspace, e+1 # [hidden]
#/# bind = $mod+Shift, Page_↑/↓,, # Window: move to workspace left/right
bind = $mod+Alt, Page_Down, split-movetoworkspace, e+1 # [hidden]
bind = $mod+Alt, Page_Up, split-movetoworkspace, e-1 # [hidden]
bind = $mod+Shift, Page_Down, split-movetoworkspace, e+1  # [hidden]
bind = $mod+Shift, Page_Up, split-movetoworkspace, e-1  # [hidden]
