# vim: filetype=hyprlang
# Ref https://wiki.hyprland.org/Configuring/Workspace-Rules/

# Window prompts
windowrule {
  name=Focus_Prompt
  float=on
  pin=1
  dim_around=1
  center=1
  rounding=10
  stay_focused=on
  focus_on_activate=on
  match:class=^((org\.kde\.polkit)|(gcr-prompter)|(org\.freedesktop\.impl\.portal\.desktop\.kde)|(org\.kde\.kwalletd)|(hyprpolkitagent)|(hyprland-share-picker)|(pinentry-))
  animation=popin
}

# Firefox Picture-in-Picture
windowrule {
  name=PiP
  float=yes
  pin=yes
  content=video
  persistent_size=off
  idle_inhibit=always
  # min_size=100 100
  rounding=10
  #keep_aspect_ratio=on
  match:title=(Picture-in-Picture)
}

# Steam client
# Match all the steam windows
windowrule {
    name=steam_client
    monitor=desc:$mon_dell_1
    match:class=^(steam)$
    pseudo=on
}
# Match friends pop up
windowrule {
    name=steam_client_friends
    match:title=(Friends List)
    match:class=^(steam)$
    float=on
    size=450 650
}

# Steam Games
windowrule {
  name=steam_games
  focus_on_activate=on
  no_dim=on
  no_anim=on
  no_blur=on
  no_shadow=on
  opaque=on
  sync_fullscreen=on
  border_size=0
  immediate=on
  pseudo=on
  content=game
  workspace=emptynm
  idle_inhibit=always
  content=game
  group=deny
  monitor=desc:$mon_gigabyte
  match:class=^(steam_app).*
}
# Fullscreen Games
windowrule {
  name=steam_games_fullscreen
  render_unfocused=on
  match:tag=steam_app
  match:fullscreen=1
}
# Sets gamescope always as fullscreen
windowrule {
  name=gamescope
  fullscreen_state=2 2,
  opacity=1 1,
  no_dim=on
  no_anim=on
  no_blur=on
  no_shadow=on
  opaque=on
  border_size=0
  group=deny
  idle_inhibit=always
  monitor=desc:$mon_gigabyte
  workspace=emptynm
  match:class=gamescope
}

# Move to social workspace
windowrule {
  name=social
  workspace=special:social
  match:title=^((WhatsApp Web)|(org\.telegram\.desktop)|(telegram)|(discord)|(com\.discord\.Discord))
}
# Move thunderbird to its own workspace on the vertical monitor
windowrule=match:class ^org.mozilla.Thunderbird$, monitor desc:$mon_dell_1

