globinclude kitty.d/**/*.conf
envinclude KITTY_CONF_*
url_style curly
open_url_with default
detect_urls yes
tab_bar_style powerline
background_opacity 0.8
enabled_layouts tall:bias=50;full_size=1;mirrored=false

map ctrl+[ layout_action decrease_num_full_size_windows
map ctrl+] layout_action increase_num_full_size_windows
map ctrl+/ layout_action mirror toggle
map ctrl+y layout_action mirror true
map ctrl+n layout_action mirror false


# BEGIN_KITTY_FONTS
font_family      family="Cascadia Mono NF"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS